### ISSUE TITLE
Error while pushing the app on SCP

### ISSUE THREAD

**Issue by jtalreja** [dirigiblelabs/deployment-sap-cloud-foundry#1]
Hi,

I have followed the steps mentioned but while pushing the application on SCP getting below error

"For application 'dirigible': Routes cannot be mapped to destinations in different spaces"

Please suggest what could be the reason?

Thanks,
Jitesh

**Comment by ThuF** [comment]
@jtalreja Hi Jitesh,

This seems like an issue with the provided configuration parameters 🤔 

Have you replaced the `subdomain` [variable](https://github.com/dirigiblelabs/deployment-sap-cloud-foundry/blob/master/dirigible/vars.yaml#L2) with the subdomain of your subaccount  in SCP _(e.g. abcd1234trial)_?

You can send us a mail to dirigible-dev@eclipse.org, so I could invite you to our Slack workspace, where we can discuss the issue in more details.

Regards,
Yordan

**Comment by jtalreja** [comment]
Thanks for your reply. I performed the following:

1. Created a clone of git

2. Changed the configuration files as per my SCP account details.
Application Name, Subaccount and Region

3. While Pushing the yaml file using cli, I observed two things - if
application name in config files is "dirigible" then I get a message "You
cannot create a route in different space". However, Role Collection and
application gets created in Cloud Foundry Space but without a route.
Secondly, if I change the application name to something else then route
gets created but I keep getting a message of some of the files being used
by another process in CLI. I can see the application and the route in my
SCP account but application is always in stopped state and cannot be
started.

Any help would be appreciated

Regards,
Jitesh

**Comment by ThuF** [comment]
@jtalreja Just drop us a mail at: dirigible-dev@eclipse.org and we will schedule a meeting to tackle the issue together.

I guess you've already went through this blog: [How to deploy Eclipse Dirigible in the SAP Cloud Platform Cloud Foundry environment](https://blogs.sap.com/2020/03/15/how-to-deploy-eclipse-dirigible-in-the-sap-cloud-platform-cloud-foundry-environment/), but I'm sharing it just in case.

Alternatively you can try to deploy it with the following command:
```
cf push <application-name> \
--docker-image=dirigiblelabs/dirigible-sap-cf \
--hostname <application-name>-<org-name> \
-m 2G -k 2G​
```

> Note: It's expecting to have 2GB of free memory (application runtime) and 2 GB storage. The same configuration is set by default in the `vars.yaml` file also. Of course you can try to update the memory and storage settings to e.g. 1GB.

It's taken from this blog post: [How to deploy an Eclipse Dirigible private Docker image in the SAP Cloud Platform Cloud Foundry environment
](https://blogs.sap.com/2020/11/20/how-to-deploy-eclipse-dirigible-private-docker-image-in-the-sap-cloud-platform-cloud-foundry-environment/)

**Comment by jtalreja** [comment]
Thanks Yordan.

I tried sending email at dirigible-dev@eclipse.org but it got rejected.
Yes, you are correct I referred the blog shared by you. Also, when I
execute the command, it says hostname parameter is not valid.

As of now, this is the only application I am trying to deploy so I have
enough resources available in my account.

Please guide how can we connect and when?

Regards,
Jitesh

**Comment by ThuF** [comment]
Try to reach out to me at: yordan.pavlov@sap.com

**Comment by ThuF** [comment]
**Fixed** - the issue was that the `cf push` command was not executed in the cloned repository directory, where the `manifest.yaml` file is located.
