### ISSUE TITLE
Token Expired

### ISSUE THREAD

**Issue by raagulto** [dirigiblelabs/deployment-sap-cloud-foundry#2]
Hello,

Dirigible IDE was working fine then suddenly we are not able to access the UI anymore.

We found this error in the logs of the SAP BTP Cockpit. 
2022-11-03 11:43:44.054 [ERROR] [http-nio-8080-exec-9] o.e.dirigible.oauth.utils.JwtUtils - The Token has expired on 2022-11-02T18:50:04Z. com.auth0.jwt.exceptions.TokenExpiredException: The Token has expired on 2022-11-02T18:50:04Z.

Is there any way to check how to re-generate or where to get the token?

Thanks!

**Comment by ThuF** [comment]
Hi @raagulto,

Please try to refresh the browser or to open the Eclipse Dirigible IDE in an incognito window.
This should be enough to request new OAuth access token.

Please also don't hesitate to join our Slack Workspace, where we gather the whole Dirigible community to interact faster: https://slack.dirigible.io

Also you could report issues (like this one and others related to Eclipse Dirigible) on the main GitHub repository: https://github.com/eclipse/dirigible

Regards,
Yordan

**Comment by raagulto** [comment]
Thanks @ThuF will move my issue to the main github.

Thanks again!

**Comment by ThuF** [comment]
Transferred to:
- https://github.com/eclipse/dirigible/issues/2197
